version: "3.9"

services:
  greenpeace-exceso-desmontes:
    image: greenpeace/exceso-desmontes
    container_name: greenpeace-exceso-desmontes
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      - PORT=3000
